---
version: "3"

vars:
  CHANNEL: '{{ default "stable" .CHANNEL }}'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  build:
    desc: |-
      task APP=<app> CHANNEL=<channel> build
    vars:
      MULTIPLATFORM: '{{ default "false" .MULTIPLATFORM }}'
    cmds:
      - >-
        docker buildx build --progress=plain --load
        -t {{.APP}}:{{.CHANNEL}}
        --build-arg CHANNEL={{.CHANNEL}}
        --build-arg VERSION=$(python ./apps/{{.APP}}/ci/latest.py "{{.CHANNEL}}")
        {{if eq .MULTIPLATFORM "true"}}
        --platform $(yq '.channels[] | select(.name=="{{.CHANNEL}}").platforms | join(",")' ./apps/{{.APP}}/metadata.json)
        {{else}}
        --platform "linux/$(uname -m | sed 's/x86_64/amd64/')"
        {{end}}
        -f ./apps/{{.APP}}/Dockerfile ./apps/{{.APP}}

  test:
    desc: |-
      task APP=<app> CHANNEL=<channel> BASE=<true/false> test
    cmds:
      - task: download-goss
      - >-
        cue vet --schema '#Spec' ./apps/{{.APP}}/metadata.yaml .ci/lint/metadata.rules.cue
      - task: build
      - >-
        ./.goss/dgoss run {{.APP}}:{{.CHANNEL}} {{if eq .BASE "true"}}tail -f /dev/null{{end}}
    env:
      CONTAINER_RUNTIME: docker
      GOSS_PATH: ./.goss/goss
      GOSS_OPTS: --sleep 5s --retry-timeout 60s --color --format documentation
      GOSS_SLEEP: 2
      GOSS_FILE: ./apps/{{.APP}}/ci/goss.yaml

  download-goss:
    silent: true
    vars:
      # renovate: datasource=github-releases depName=aelsabbahy/goss versionTemplate=^(?<version>.*)$
      GOSS_VERSION: v0.4.1
    cmds:
      - mkdir -p ./.goss
      - curl -fsSL -o ./.goss/goss https://github.com/aelsabbahy/goss/releases/download/{{.GOSS_VERSION}}/goss-linux-amd64
      - chmod +x ./.goss/goss
      - curl -fsSL -o ./.goss/dgoss https://raw.githubusercontent.com/aelsabbahy/goss/{{.GOSS_VERSION}}/extras/dgoss/dgoss
      - chmod +x ./.goss/dgoss
    status:
      - test -f ./.goss/goss
      - test -f ./.goss/dgoss
