---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docker: Build and Push"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/**
  pull_request:
    paths:
      - apps/**

jobs:
  get-changed-images:
    name: Determine changed images
    runs-on: ubuntu-latest
    outputs:
      changed_images: ${{ steps.filter-containers.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine changed images
        uses: tj-actions/changed-files@v45
        id: filter-containers
        with:
          dir_names: true
          dir_names_max_depth: "1"
          path: apps
          separator: ","

      - name: Add summary
        env:
          CHANGED_IMAGES: "${{ steps.filter-containers.outputs.all_changed_files }}"
        run: |
          IFS=',' read -a images <<< "${CHANGED_IMAGES}"
          echo "### Changed images:" > "$GITHUB_STEP_SUMMARY"
          for image in ${images[@]}; do
            echo "- ${image}" >> "$GITHUB_STEP_SUMMARY"
          done

  generate-matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    needs:
      - get-changed-images
    steps:
      # - name: Generate Token
      #   uses: actions/create-github-app-token@v1
      #   if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      #   id: app-token
      #   with:
      #     app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
      #     private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   token: "${{ steps.app-token.outputs.token }}"

      - name: Install dependencies
        run: npm install

      - name: Generate matrix
        run: npm run genmatrix
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          INCLUDE_IMAGES: ${{ steps.filter-containers.outputs.all_changed_files }}

      - name: Save Matrix
        id: matrix
        run: |
          matrix=$(cat matrix.json)
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  build:
    name: build ${{ matrix.job_name }}
    needs:
      - generate-matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/workflow_call-build_image.yaml
    with:
      image: |
        ghcr.io/bjw-s/${{ matrix.job_name }}
        ghcr.io/bjw-s-labs/${{ matrix.job_name }}
    # steps:
    #   - name: Debug
    #     run: |
    #       echo ${{ matrix.job_name }}

  # build:
  #   name: Build ${{ matrix.job_name }}
  #   needs:
  #     - generate-matrix
  #   uses: ./.github/workflows/workflow_call-build_image.yaml
  #   if: ${{ fromJson(needs.generate-matrix.outputs.matrix)['include'].length > 0 }}
  #   strategy:
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix)['include'] }}
  #   secrets: inherit
  #   with:
  #     image: |
  #       ghcr.io/bjw-s/${{ matrix.image_name }}
  #       ghcr.io/bjw-s-labs/${{ matrix.image_name }}
  #     platforms: ${{ matrix.platforms }}
  #     tags: |
  #       type=semver,pattern={{version}},value=${{ matrix.version }}
  #       type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
  #       type=semver,pattern={{major}},value=${{ matrix.version }}
  #     context: ${{ matrix.context }}
  #     dockerfile: ${{ matrix.dockerfile }}
  #     dry-run: true
