---
name: "Workflow call: Render Readme"

on:
  workflow_call:
    secrets:
      BJWS_APP_ID:
        description: "The App ID of the GitHub App"
        required: true
      BJWS_APP_PRIVATE_KEY:
        description: "The private key of the GitHub App"
        required: true

jobs:
  render-readme:
    name: Render README
    runs-on: ubuntu-latest
    steps:
      - name: "Generate Short Lived OAuth App Token (ghs_*)"
        uses: actions/create-github-app-token@v1.6.1
        id: app-token
        with:
          app-id: "${{ secrets.BJWS_APP_ID }}"
          private-key: "${{ secrets.BJWS_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Install Python Requirements
        run: |
          pip install -r ./.ci/scripts/requirements.txt && pip freeze

      - name: Render README
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          python ./.ci/scripts/render-readme.py

      - name: Commit Changes
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          FILE_TO_COMMIT: "README.md"
          DESTINATION_BRANCH: "main"
        run: |
          export TODAY=$(date -u '+%Y-%m-%d')
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY [skip ci]"
          export SHA=$(git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT)
          export CONTENT=$(base64 -i $FILE_TO_COMMIT)
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA" \
            || echo "No changes to push"
