---
name: "Workflow call: Get Changed Images"

on:
  workflow_call:
    outputs:
      addedOrModifiedImages:
        description: "The images that were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModifiedImages }}

jobs:
  get-changed-images:
    name: Get Changed Images
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: "${{ steps.filter-containers.outputs.all_changed_files }}"
    steps:
      - uses: actions/checkout@v4

      - name: Determine changed images
        uses: tj-actions/changed-files@v45
        id: filter-containers
        with:
          dir_names: true
          dir_names_max_depth: "1"
          path: apps
          separator: ","

      - name: Summarize step
        env:
          CHANGED_IMAGES: "${{ steps.filter-containers.outputs.all_changed_files }}"
        run: |
          IFS=',' read -a images <<< "${CHANGED_IMAGES}"
          echo "### Changed images:" > "$GITHUB_STEP_SUMMARY"
          for image in ${images}; do
            echo "- ${image}" >> "$GITHUB_STEP_SUMMARY"
          done
