---
name: "Workflow call: Get Changed Images"

on:
  workflow_call:
    outputs:
      addedOrModifiedImages:
        description: "The images that were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModifiedImages }}

jobs:
  get-changed-images:
    name: Get Changed Images
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: "${{ steps.filter-containers.outputs.addedOrModifiedImages }}"
    steps:
      - uses: actions/checkout@v4

      - name: Collect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            addedOrModified:
              - added|modified: 'apps/*/**'

      - name: Determine changed images
        if: ${{ steps.filter.outputs.addedOrModified == 'true' }}
        id: filter-containers
        run: |
          PATHS='${{ steps.filter.outputs.addedOrModified_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/")[1]) | unique | join(",")')
          echo "addedOrModifiedImages=${OUTPUT}" >> $GITHUB_OUTPUT
